src/TBSBundle/Entity/TbsManagers.php
<?php

namespace Time\TBSBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * Tbs_Managers
 *
 * @ORM\Table(name="tbs_manager")
 * @ORM\Entity(repositoryClass="Time\TBSBundle\Repository\TbsManagersRepository")
 */
class TbsManagers
{
    use ORMBehaviors\Blameable\Blameable,
        ORMBehaviors\Timestampable\Timestampable;
    /**
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="active", type="integer")
     */
    private $active;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set active
     *
     * @param integer $active
     *
     * @return TbsManagers
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return integer
     */
    public function getActive()
    {
        return $this->active;
    }
    /**
     * @ORM\ManyToOne(targetEntity="Time\TBSBundle\Entity\TbsPole", cascade={"persist"} )
     *@ORM\JoinColumn(name="tbs_pole_id", referencedColumnName="id")
     */
    private $tbs_pole;
    /**
     * @ORM\ManyToOne(targetEntity="Time\TBSBundle\Entity\TbsUser", cascade={"persist"} )
     *@ORM\JoinColumn(name="tbs_user_id", referencedColumnName="id")
     */
    private $tbs_User;

    /**
     * @return mixed
     */
    public function getTbsPole()
    {
        return $this->tbs_pole;
    }

    /**
     * @param mixed $tbs_pole
     */
    public function setTbsPole($tbs_pole)
    {
        $this->tbs_pole = $tbs_pole;
    }

    /**
     * @return mixed
     */
    public function getTbsUser()
    {
        return $this->tbs_User;
    }

    /**
     * @param mixed $tbs_User
     */
    public function setTbsUser($tbs_User)
    {
        $this->tbs_User = $tbs_User;
    }

    public function __toString()
    {
       return $this->getTbsUser()->getUser()->getDisplayName();
    }


}

src/TBSBundle/Entity/TbsUser.php
<?php

namespace Time\TBSBundle\Entity;
use DateTime;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Doctrine\ORM\Mapping as ORM;

/**
 * Tbs_User
 *
 * @ORM\Table(name="tbs_user")
 * @ORM\Entity(repositoryClass="Time\TBSBundle\Repository\TbsUserRepository")
 */
class TbsUser
{
    use ORMBehaviors\Blameable\Blameable,
        ORMBehaviors\Timestampable\Timestampable;
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="weekly_working_hours", type="time")
     */
    private $weeklyWorkingHours;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="period", type="date")
     */
    private $period;

    /**
     * @var integer
     *
     * @ORM\Column(name="capacity_percent", type="integer")
     */
    private $capacityPercent;

    /**
     * @ORM\ManyToOne(targetEntity="Time\TBSBundle\Entity\TbsService", cascade={"persist"} )
     *@ORM\JoinColumn(name="tbs_service_id", referencedColumnName="id")
     */
    private $tbs_service;

    /**
     * @ORM\ManyToOne(targetEntity="User\UserBundle\Entity\User", cascade={"persist"} )
     *@ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;
    /**
     * @ORM\ManyToOne(targetEntity="Time\TBSBundle\Entity\TbsPole", cascade={"persist"} )
     *@ORM\JoinColumn(name="tbs_pole_id", referencedColumnName="id")
     */
    private $tbs_pole;
    /**
     * @ORM\ManyToOne(targetEntity="Time\TBSBundle\Entity\TbsPoste", cascade={"persist"} )
     *@ORM\JoinColumn(name="tbs_poste_id", referencedColumnName="id")
     */
    private $tbs_poste;
     private $taux;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    private $pays;
    /**
     * Set weeklyWorkingHours
     *
     * @param \DateTime $weeklyWorkingHours
     *
     * @return TBS_USER
     */
    public function setWeeklyWorkingHours($weeklyWorkingHours)
    {
        $this->weeklyWorkingHours = $weeklyWorkingHours;

        return $this;
    }

    /**
     * Get weeklyWorkingHours
     *
     */
    public function getWeeklyWorkingHours()
    {
        /**
         * Intialisation of the first date
         */
        $date_first = new DateTime('1970-01-01');
        $diff = $date_first->diff($this->weeklyWorkingHours);
        $hours = $diff->h;
        $hours = $hours + ($diff->days*24);
        return $hours;
    }

    /**
     * Set period
     *
     * @param \DateTime $period
     *
     * @return TBS_USER
     */
    public function setPeriod($period)
    {
        $this->period = $period;

        return $this;
    }

    /**
     * Get period
     *
     * @return \DateTime
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * Set capacityPercent
     *
     * @param integer $capacityPercent
     *
     * @return TBS_USER
     */
    public function setCapacityPercent($capacityPercent)
    {
        $this->capacityPercent = $capacityPercent;

        return $this;
    }

    /**
     * Get capacityPercent
     *
     * @return integer
     */
    public function getCapacityPercent()
    {
        return $this->capacityPercent;
    }

    /**
     * @return mixed
     */
    public function getTbsService()
    {
        return $this->tbs_service;
    }

    /**
     * @param mixed $tbs_service
     */
    public function setTbsService($tbs_service)
    {
        $this->tbs_service = $tbs_service;
    }

    /**
     * @return mixed
     */
    public function getTbsPole()
    {
        return $this->tbs_pole;
    }

    /**
     * @param mixed $tbs_pole
     */
    public function setTbsPole($tbs_pole)
    {
        $this->tbs_pole = $tbs_pole;
    }

    /**
     * @return mixed
     */
    public function getTbsPoste()
    {
        return $this->tbs_poste;
    }

    /**
     * @param mixed $tbs_poste
     */
    public function setTbsPoste($tbs_poste)
    {
        $this->tbs_poste = $tbs_poste;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getPays()
    {
        return $this->user->getCountryWorking();
    }

    /**
     * @param mixed $pays
     */
    public function setPays($pays)
    {
        $this->user->setCountryWorking($pays) ;
    }

    /**
     * @return mixed
     */
    public function getTaux()
    {
        return $this->tbs_poste->getHourlyRate();
    }

    /**
     * @param mixed $taux
     */
    public function setTaux($taux)
    {
        $this->tbs_poste->setHourlyRate($taux);
    }
    public function __toString()
    {
        return $this->getUser()->getDisplayName();
    }


}

src/TBSBundle/Resources/views/Admin/addPole.html.twig
<div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Ajouter un pôle</h4>
</div>
<div class="modal-body">
    <div class="form-horizontal">
        {{ form_start(form,{'action': path('time_tbs_admin_newPole'), 'method': 'POST'}) }}


        <div class="form-group">
            <label class="control-label col-sm-4 col-md-4" for="pwd">Libellé :</label>
            <div class="col-sm-8 col-md-6">
                <label class="control-label" for="pwd" >{{  form_widget (form.name ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4 col-md-4" for="pwd">Manager(s):</label>
            <div class="col-sm-8 col-md-6">
                <label class="control-label" for="pwd" style="width: 200px!important;" >{{ form_widget (form.manager ,{'attr':{'class':'js-example-responsive '}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2 col-md-offset-4">
                <input type="submit" value="Ajouter" class="btn btn-primary">
            </div>
        </div>
        {{ form_end (form) }}
    </div>
</div>

<script>
    $(".modal").on('hidden.bs.modal', function () {
        $(".modal-body").html("");
        $(this).data('bs.modal', null);
    });
    $(document).ready(function() {
        $('.js-example-responsive').select2({
            width: 'resolve'
        });
    });
</script>

src/TBSBundle/Resources/views/Admin/addPoste.html.twig
<div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Ajouter un Poste</h4>
</div>
<div class="modal-body">
    <div class="form-horizontal">
        {{ form_start(form,{'action': path('time_tbs_admin_newPoste'), 'method': 'POST'}) }}
        <div class="form-group">
            <label class="control-label col-sm-4 col-md-4" for="pwd">Libéllé :</label>
            <div class="col-sm-8 col-md-8">
                <label class="control-label"
                       for="pwd">{{ form_widget (form.name ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2 col-md-offset-4">
                <input type="submit" value="Ajouter" class="btn btn-primary">
            </div>
        </div>
        {{ form_end (form) }}
    </div>
</div>

src/TBSBundle/Resources/views/Admin/edit.html.twig
<div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Modifier le collaborateur</h4>
</div>
<div class="modal-body">
    <div class="form-horizontal">
        {{ form_start(form,{'action': path('time_tbs_admin_edit',{'id':user_tbs.id}), 'method': 'POST'}) }}

        <div class="form-group">
            <label class="control-label col-sm-6" for="pwd">NOM Prénom :</label>
            <div class="col-sm-6">
                <label class="control-label" for="pwd" >{{ user_tbs.user.displayName }}</label>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-6" for="pwd">Base horaire hebdomadaire :</label>
            <div class="col-sm-6">
                <label class="control-label" for="pwd" >{{  form_widget (form.weeklyWorkingHours ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-6" for="pwd">Pays :</label>
            <div class="col-sm-6">
                <label class="control-label" for="pwd" >{{ form_widget (form.pays ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-6" for="pwd">Pôle :</label>
            <div class="col-sm-6">
                {{ form_widget(form.tbs_pole ,{'attr':{'class':'form-control'}}) }}

            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-6" for="pwd">Poste :</label>
            <div class="col-sm-6">
                {{ form_widget(form.tbs_poste ,{'attr':{'class':'form-control'}}) }}

            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-6" for="pwd">Part de l'activité planifiable (en%):</label>
            <div class="col-sm-6">
                <label class="control-label" for="pwd" >{{ form_widget (form.capacityPercent ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-6" for="pwd">Taux horaire:</label>
            <div class="col-sm-6">
                <label class="control-label" for="pwd" >{{ form_widget (form.taux ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2 col-md-offset-4">
                <input type="submit" value="Modifier" class="btn btn-primary">
            </div>
        </div>
        {{ form_end (form) }}
    </div>
</div>

    <script>
    $(".modal").on('hidden.bs.modal', function () {
        $(".modal-body").html("");
        $(this).data('bs.modal', null);
    });
</script>

src/TBSBundle/Resources/views/Admin/editPole.html.twig
<div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Modifier un pôle</h4>
</div>
<div class="modal-body">
    <div class="form-horizontal">
        {{ form_start(form,{'action': path('time_tbs_admin_editPole',{'id':pole.id}), 'method': 'POST'}) }}
        <div class="form-group">
            <label class="control-label col-sm-4 col-md-4" for="pwd">Libellé :</label>
            <div class="col-sm-8 col-md-8">
                <label class="control-label" for="pwd"  >{{ form_widget (form.name ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4 col-md-4" for="pwd">Manager(s):</label>
            <div class="col-sm-8 col-md-8">
                <label class="control-label" for="pwd" style="width: 200px!important;" >{{ form_widget (form.manager ,{'attr':{'class':'js-example-responsive '}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-6 col-md-offset-4">
                <input type="submit" value="Modifier" class="btn btn-primary">
                {% if supp %}
                    <a href="#" class="btn btn-danger"
                       disabled="true">Supprimer</a>
                    <span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="right"
                          title="Ce Pôle ne peut être supprimé car un utilisateur (au moins) y est encore affecté. Pour pouvoir être supprimé, ce pôle doit être vide."></span>
                {% else %}
                    <a href="{{ path('time_tbs_admin_removePole',{'id':pole.id}) }}"
                       class="btn btn-danger">Supprimer</a>
                {% endif %}
            </div>
        </div>
        {{ form_end (form) }}
    </div>
</div>

<script>
    $(".modal").on('hidden.bs.modal', function () {
        $(".modal-body").html("");
        $(this).data('bs.modal', null);
    });
    $(document).ready(function() {
        $('.js-example-responsive').select2({
            width: 'resolve'
        });
    });
</script>

src/TBSBundle/Resources/views/Admin/editPoste.html.twig
<div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Modifier un Poste</h4>
</div>
<div class="modal-body">
    <div class="form-horizontal">
        {{ form_start(form,{'action': path('time_tbs_admin_editPoste',{'id':poste.id}), 'method': 'POST'}) }}
        <div class="form-group">
            <label class="control-label col-sm-4 col-md-4" for="pwd">Libéllé :</label>
            <div class="col-sm-8 col-md-8">
                <label class="control-label"
                       for="pwd">{{ form_widget (form.name ,{'attr':{'class':'form-control'}}) }}</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-6 col-md-offset-4">
                <input type="submit" value="Modifier" class="btn btn-primary">
                {% if supp %}
                    <a href="#" class="btn btn-danger"
                       disabled="true">Supprimer</a>
                    <span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="right"
                          title="Ce Poste ne peut être supprimé car un utilisateur (au moins) y est encore affecté. Pour pouvoir être supprimé, ce poste doit être vide."></span>
                {% else %}
                    <a href="{{ path('time_tbs_admin_removePoste',{'id':poste.id}) }}"
                       class="btn btn-danger">Supprimer</a>
                {% endif %}
            </div>
        </div>
        {{ form_end (form) }}
    </div>
</div>

{#<script>#}
    {#$(".modal").on('hidden.bs.modal', function () {#}
        {#$(".modal-body").html("");#}
        {#$(this).data('bs.modal', null);#}
    {#});#}
{#</script>#}

src/TBSBundle/Resources/views/Admin/index.html.twig
{% extends "TimeTBSBundle::layout.html.twig" %}

{% block title %}
    Accueil {{ parent() }}
{% endblock %}
{% block extraStylesheets %}
    <link href="{{ asset('bundles/timetbs/css/style-tbs.css') }} " rel="stylesheet" type="text/css">
{% endblock %}

{% block body %}

    <section class="content-header">
        <h1>Collaborateurs</h1>
        <div class="box-body">
            <div class="box bottomScrool">

                <div class="box-body">
                    <div id="listDemandes_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <table class="table table-condensed dataTable no-footer" style="background-color:#ffffff" role="grid">
                            <thead>
                            <tr role="row">
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">NOM Prénom</th>
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">Base horaire hebdomadaire</th>
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">Pays</th>
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">Pôle</th>
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">Poste</th>
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">Taux horaire</th>
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">Part de l'activité planifiable (en %)</th>
                                <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1">Action</th>
                            </tr>
                            </thead>
                            <tbody role="alert" aria-live="polite" aria-relevant="all">
                            {% for user in users %}
                            <tr role="row" class="odd">
                                <td class="showCol">{{ user.user.displayName }} </td>
                                <td>{{ (user.WeeklyWorkingHours) }}</td>
                                <td>{{ user.user.CountryWorking|upper }}</td>
                                <td> {% if user.TbsPole != null  %}{{ user.TbsPole.Name }}
                                {% else %} -
                                {% endif %}</td>
                                <td>{% if user.TbsPoste != null  %}{{ user.TbsPoste.Name }}
                                    {% else %} -
                                    {% endif %}</td>
                                <td>{{ user.TbsPoste.HourlyRate }}</td>
                                <td>{{ user.capacityPercent }}</td>
                                <td>
                                    <a href="{{ path('time_tbs_admin_edit',{'id':user.id}) }}" class="btn btn-primary a-btn-slide-text" data-toggle="modal" data-target="#setCollab">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                        <span><strong>Edit</strong></span>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {#<div class="navigation">#}
                            {#{{ knp_pagination_render(paginations) }}#}
                        {#</div>#}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="setCollab" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">

					</div>
                </div>
            </div>
    </div>





{% endblock %}
    {% block extraJavascripts %}
        <script type="text/javascript" src="{{ asset('all/DataTables/datatables.js') }}"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
        <script>
            $(function () {
                var datatable = $('.dataTable').DataTable({
                    "dom": '<"top"i>rt<"bottom"flp><"clear">',
                    language: {
                        emptyTable: "<span class='text-blue'><b>Aucune donnée disponible</b></span>",
                        info: "<h4>-- _MAX_ résultats.</h4>",
                    },
                    order: [[0, "desc"]], // order by demandeId at first
                    bPaginate: false, // remove pagination
                    bInfo: true, // remove total no of results
                    bFilter: false //  search box
                });
                $('.dataTable').css({'width': '100%'});
            });
        </script>
        <script type="text/javascript"
                src="{{ asset ('bundles/timetbs/js/bootstrap-datepicker.js') }}"></script>
        <script type="text/javascript"
                src="{{ asset('bundles/timetbs/js/bootstrap-datepicker.fr.js') }}"></script>
        <script>
            $(function () {
                $('#datePicker').datepicker({
                    format: 'yyyy-mm',
                    clearBtn: true,
                    language: "fr",
                    minViewMode: "months"
                });
                $('#datePicker').on('changeDate', function () {
                    var date = $('#datepicker').val();
                    route = "{{ path('time_tbs_filter_manager',{'date': 'PLACEHOLDER'}) }}";
                    return window.location.href = route.replace("PLACEHOLDER", date);
                });
            });
        </script>
       <script>
           $(".modal").on('hidden.bs.modal', function () {
               $(this).data('bs.modal', null);
           });
       </script>

    {% endblock %}

src/TBSBundle/Resources/views/Admin/service.html.twig
{% extends "TimeTBSBundle::layout.html.twig" %}

{% block title %}
    Accueil {{ parent() }}
{% endblock %}
{% block extraStylesheets %}
    <link href="{{ asset('bundles/timetbs/css/style-tbs.css') }} " rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/timetbs/css/select2.css') }}" rel="stylesheet"/>

{% endblock %}

{% block body %}

    <section class="content">
        <section id="polesection" class="content-header col-md-6">
            <h1>Pôles</h1>
            <div class="box-body">
                <div class="box bottomScrool">
                    <div class="box-body">
                        <div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <table class="table table-condensed dataTable no-footer"
                                   style="background-color:#ffffff" role="grid">
                                <thead>
                                <tr role="row">
                                    <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1"
                                        aria-sort="ascending" aria-label="#: activate to sort column descending">
                                        Libéllé
                                    </th>
                                    <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1"
                                        aria-sort="ascending" aria-label="#: activate to sort column descending">
                                        Manager
                                    </th>
                                    <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1"
                                        aria-label="Titre: activate to sort column ascending">Action
                                    </th>
                                </tr>
                                </thead>
                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                {% for pole in poles %}
                                    <tr role="row" class="odd">
                                        <td class="showCol">{{ pole.name }}</td>
                                        <td class="showCol">{% for manager in managers %}
                                                {% if pole == manager.tbsPole %}
                                                    {{ manager.tbsUser.user.displayName }} <br> {% endif %}
                                            {% endfor %}</td>
                                        <td>
                                            <a href="{{ path('time_tbs_admin_editPole',{'id':pole.id}) }}"
                                               class="btn btn-primary a-btn-slide-text" data-toggle="modal"
                                               data-target="#Editpole">
                                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                <span><strong>Edit</strong></span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            <div>
                                <a href="{{ path('time_tbs_admin_newPole') }}" class="btn btn-primary a-btn-slide-text"
                                   data-toggle="modal"
                                   data-target="#newpole">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                    <span><strong>Ajouter</strong></span>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="content-header col-md-6">
            <h1>Postes</h1>
            <div class="box-body">
                <div class="box bottomScrool">
                    <div class="box-body">
                        <div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <table class="table table-condensed dataTable no-footer"
                                   style="background-color:#ffffff" role="grid">
                                <thead>
                                <tr role="row">
                                    <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1"
                                        aria-sort="ascending" aria-label="#: activate to sort column descending">
                                        Libéllé
                                    </th>
                                    <th style="cursor: pointer" class="showCol" rowspan="1" colspan="1"
                                        aria-label="Titre: activate to sort column ascending">Action
                                    </th>
                                </tr>
                                </thead>
                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                {% for poste in postes %}
                                    <tr role="row" class="odd">
                                        <td class="showCol">{{ poste }}</td>
                                        <td>
                                            <a href="{{ path('time_tbs_admin_editPoste',{'id':poste.id}) }}"
                                               class="btn btn-primary a-btn-slide-text" data-toggle="modal"
                                               data-target="#Editposte">
                                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                <span><strong>Edit</strong></span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div>
                                <a href="{{ path('time_tbs_admin_newPoste') }}" class="btn btn-primary a-btn-slide-text"
                                   data-toggle="modal"
                                   data-target="#newposte">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                    <span><strong>Ajouter</strong></span>
                                </a>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
    <div class="modal fade" id="newpole" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">

                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="newposte" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">

                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="Editpole" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="Editposte" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#F5F5F5;border-radius:4px;">

                </div>
            </div>
        </div>
    </div>


{% endblock %}